name: Docker Image C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  juputer-pythn-project:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: maigoescode/data_science_projects
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
